### ISSUE TITLE
Can't get transcode to work

### ISSUE THREAD

**Issue by Troubadoure** [magn2o/unicorn-docker#7]
I'm really struggling to get this up and running. I've installed the load balancer on 10.0.0.75 and the transcoder on 10.0.0.81. I can direct play from 10.0.0.75 but can't seem to transcode anything.

My docker-compose files:

Loadbalancer:
```
version: '3'

services:
  plex:
    container_name: unicorn-plex
    image: plexinc/pms-docker:latest
    networks:
      - plex-network
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    hostname: Node
    environment:
      - TZ=Europe/London
      - ADVERTISE_IP=http://10.0.0.75:3001/
      - LB_URL=http://loadbalancer:3001/
      - PLEX_CLAIM=xxxxxxxxxxxxx
      - PLEX_UID=1024
      - PLEX_GID=100    
    volumes:
      - binaries:/usr/lib/plexmediaserver
      - ./PMS/database:/config
      - /volume1/Plex:/media:ro
    restart: unless-stopped

  loadbalancer:
    container_name: unicorn-loadbalancer
    image: magn2o/unicorn-loadbalancer:latest
    depends_on:
      - plex
      - redis
    networks:
      - plex-network
    ports:
      - 3001:3001/tcp
    environment:
      - SERVER_HOST=127.0.0.1
      - SERVER_PORT=3001
      - SERVER_PUBLIC=http://10.0.0.75:3001/
      - PLEX_HOST=plex
      - PLEX_PORT=32400
      - PLEX_PATH_SESSIONS=/config/Library/Application Support/Plex Media Server/Cache/Transcode/Sessions
      - DATABASE_SQLITE_PATH=/config/Library/Application Support/Plex Media Server/Plug-in Support/Databases/com.plexapp.plugins.library.db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - LB_URL=http://loadbalancer:3001/
    volumes:
      - binaries:/usr/lib/plexmediaserver
      - ./PMS/database:/config
      - /volume1/Plex:/media:ro
    restart: unless-stopped

  redis:
    container_name: unicorn-redis
    image: redis:alpine
    networks:
      - plex-network
    sysctls:
      - net.core.somaxconn=511
    restart: unless-stopped
volumes:
    binaries:
networks:
  plex-network:
```

Transcoder:
```
version: '3'

services:
    transcoder:
        container_name: unicorn-transcoder
        image: magn2o/unicorn-transcoder:latest
        ports:
            - 3000:32400/tcp
        hostname: Node
        environment:
            - SERVER_PORT=32400
            - LOADBALANCER_ADDRESS=http://10.0.0.75:3001
            - INSTANCE_ADDRESS=http://10.0.0.81:3000
            - PLEX_TOKEN=XXXXXXXXXXXX
        restart: unless-stopped
```

Can you point me in the right direction to get this up and running?

**Comment by urwrstkn8mare** [comment]
I had to do this 

```
services:
    transcoder:
        container_name: unicorn-transcoder
        image: magn2o/unicorn-transcoder:latest
        ports:
            - 3000:3000/tcp
        hostname: Node
        environment:
            - SERVER_PORT=3000
            - LOADBALANCER_ADDRESS=http://10.0.0.75:3001
            - INSTANCE_ADDRESS=http://10.0.0.81:3000
            - PLEX_TOKEN=XXXXXXXXXXXX
        restart: unless-stopped
```
